import {
  Box,
  Lightbulb,
  Droplet,
  Monitor,
  Sofa,
  Table,
  Bed,
  ClipboardList,
  Construction,
  Lock,
  Trash2,
  Archive,
  Wrench,
  Plug,
  Fan,
  Cable,
  PaintBucket,
  ShieldCheck,
  Truck,
  Zap,
} from 'lucide-react'

export const CATEGORY_ICON_MAP = [
  { key: 'box', label: 'วัสดุทั่วไป', Icon: Box },
  { key: 'lightbulb', label: 'อุปกรณ์ไฟฟ้า', Icon: Lightbulb },
  { key: 'droplet', label: 'ประปา / สุขาภิบาล', Icon: Droplet },
  { key: 'monitor', label: 'อุปกรณ์ IT / ไฟฟ้า', Icon: Monitor },
  { key: 'sofa', label: 'เฟอร์นิเจอร์ (โซฟา)', Icon: Sofa },
  { key: 'table', label: 'โต๊ะ', Icon: Table },
  { key: 'clipboard-list', label: 'เอกสาร / รายการ', Icon: ClipboardList },
  { key: 'construction', label: 'งานซ่อมบำรุง', Icon: Construction },
  { key: 'lock', label: 'ความปลอดภัย', Icon: Lock },
  { key: 'trash-2', label: 'ของเสีย / ทิ้ง', Icon: Trash2 },
  { key: 'archive', label: 'คลังเก็บ', Icon: Archive },
  { key: 'wrench', label: 'อะไหล่ / ซ่อม', Icon: Wrench },
  { key: 'plug', label: 'ปลั๊ก / สายไฟ', Icon: Plug },
  { key: 'fan', label: 'ระบายอากาศ', Icon: Fan },
  { key: 'cable', label: 'สายสัญญาณ', Icon: Cable },
  { key: 'paint-bucket', label: 'สี / วัสดุก่อสร้าง', Icon: PaintBucket },
  { key: 'shield-check', label: 'อุปกรณ์ป้องกัน', Icon: ShieldCheck },
  { key: 'truck', label: 'ขนส่ง / เคลื่อนย้าย', Icon: Truck },
  { key: 'zap', label: 'ไฟฟ้า', Icon: Zap },
]
