import {
  Tool,
  Box,
  Lightbulb,
  Droplet,
  Monitor,
  Chair,
  Brush,
  ClipboardList,
  Construction,
  Lock,
  FireExtinguisher,
  Wrench,
  Plug,
  Fan,
  Cable,
  PaintBucket,
  ShieldCheck,
  Truck,
  Trash2,
  Archive,
} from 'lucide-react'

export const ICON_OPTIONS = [
  { key: 'tool', label: 'เครื่องมือช่าง', Icon: Tool },
  { key: 'box', label: 'วัสดุทั่วไป', Icon: Box },
  { key: 'lightbulb', label: 'อุปกรณ์ไฟฟ้า', Icon: Lightbulb },
  { key: 'droplet', label: 'ประปา / สุขาภิบาล', Icon: Droplet },
  { key: 'monitor', label: 'อุปกรณ์ IT / ไฟฟ้า', Icon: Monitor },
  { key: 'chair', label: 'เฟอร์นิเจอร์', Icon: Chair },
  { key: 'brush', label: 'ทำความสะอาด', Icon: Brush },
  { key: 'clipboard', label: 'เอกสาร / สำนักงาน', Icon: ClipboardList },
  { key: 'construction', label: 'งานซ่อมบำรุง', Icon: Construction },
  { key: 'lock', label: 'ความปลอดภัย', Icon: Lock },

  { key: 'fire', label: 'อุปกรณ์ดับเพลิง', Icon: FireExtinguisher },
  { key: 'wrench', label: 'อะไหล่ / ซ่อม', Icon: Wrench },
  { key: 'plug', label: 'ปลั๊ก / สายไฟ', Icon: Plug },
  { key: 'fan', label: 'ระบายอากาศ', Icon: Fan },
  { key: 'cable', label: 'สายสัญญาณ', Icon: Cable },
  { key: 'paint', label: 'สี / วัสดุก่อสร้าง', Icon: PaintBucket },
  { key: 'shield', label: 'อุปกรณ์ป้องกัน', Icon: ShieldCheck },
  { key: 'truck', label: 'ขนส่ง / เคลื่อนย้าย', Icon: Truck },
  { key: 'trash', label: 'ของเสีย / ทิ้ง', Icon: Trash2 },
  { key: 'archive', label: 'คลังเก็บ', Icon: Archive },
]
